version: '3'
services:
  react-app:
    image: genshin-react-app
    build: ./client/
    ports:
      - '3000:3000'
    volumes:
      - ./client/src:/app/src:ro
    # environment:
    #   - REACT_APP_NAME=test
    # env_file:
    #   - ./.env
    networks:
      - mern-app

  api-server:
    image: genshin-api-server
    build: ./server/
    ports:
      - '5000:5000'
    # environment:
    #   - PORT=5500
    volumes:
      - ./server/src:/app/src:ro
    networks:
      - mern-app
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - mern-app

networks:
  mern-app:
    driver: bridge

volumes:
  mongo-data:
    driver: local
